[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.build_lib]
run_task = [
    { name = "build_windows_msvc", condition = {platforms = ["windows"]}},
    { name = "build_unix"}
]

[tasks.build_windows_msvc]
env = { "CC" = "clang-cl", "CXX" = "clang-cl"}
toolchain = "nightly-2021-08-13"
command = "cargo"
args = ["build", "--lib"]

[tasks.build_unix]
toolchain = "nightly-2021-08-13"
command = "cargo"
args = ["build", "--lib"]

[tasks.build_bin]
run_task = [
    { name = "build_windows_msvc_bin", condition = {platforms = ["windows"]}},
    { name = "build_unix_bin"}
]

[tasks.build_windows_msvc_bin]
env = { "CC" = "clang-cl", "CXX" = "clang-cl"}
command = "cargo"
args = ["build", "--bin", "yttrium_standalone"]

[tasks.build_unix_bin]
command = "cargo"
args = ["build", "--bin", "yttrium_standalone"]

[tasks.run_suite]
dependencies = ["format", "build", "test"]