[package]
name = "unity-rs-derive"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
unity-rs = {path = "../unity-rs"}

syn = "1.0"
quote = "1.0"